# Generated by Django 3.1.7 on 2021-04-26 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieCd', models.IntegerField(primary_key=True, serialize=False)),
                ('movieNm', models.CharField(max_length=20)),
                ('genreNm', models.CharField(max_length=10)),
                ('watchGradeNm', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='watched_user',
            field=models.ManyToManyField(related_name='watched_user', through='movie.WatchedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
