# Generated by Django 3.1.7 on 2021-04-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('genre', models.CharField(max_length=10)),
                ('runtime', models.CharField(max_length=10)),
                ('plot', models.TextField()),
                ('keywords', models.CharField(max_length=50)),
                ('posterUrl', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
